// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWum_HS3FpvbIrz3vtmR1xuBdTuh1lh-Y',
    appId: '1:778442303591:web:4a2ed2d44eff1c0abd0cc2',
    messagingSenderId: '778442303591',
    projectId: 'amirnazeer-553be',
    authDomain: 'amirnazeer-553be.firebaseapp.com',
    storageBucket: 'amirnazeer-553be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7lWsKYpxG7R7jWphLDLkTeAvGcLUVkmE',
    appId: '1:778442303591:android:b62e5c5f7d9279a7bd0cc2',
    messagingSenderId: '778442303591',
    projectId: 'amirnazeer-553be',
    storageBucket: 'amirnazeer-553be.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWum_HS3FpvbIrz3vtmR1xuBdTuh1lh-Y',
    appId: '1:778442303591:web:dcd67acac963effcbd0cc2',
    messagingSenderId: '778442303591',
    projectId: 'amirnazeer-553be',
    authDomain: 'amirnazeer-553be.firebaseapp.com',
    storageBucket: 'amirnazeer-553be.firebasestorage.app',
  );
}






